version: '2'

services:
    couchdb:
        image: klaemo/couchdb:1.6
        ports:
            - "5987:5984"
        volumes:
            - ./couchdb/config:/usr/local/etc/couchdb/local.d
            - ./couchdb/log:/usr/local/var/log/couchdb
            - ./couchdb/data:/usr/local/var/lib/couchdb

    filebeat:
        image: olinicola/filebeat:1.2.3
        volumes:
            - ./couchdb/log/couch.log:/var/log/couchdb # log from couchdb
            - ./filebeat/config/filebeat.yml:/etc/filebeat/filebeat.yml
        links:
            - "elk"

    elk:
        image: sebp/elk
        ports:
            - "5601:5601" # kibana
            - "9200:9200" # elastic
            - "5044:5044" # logstash beats filebeat
        volumes:
            - ./logstash/conf.d:/etc/logstash/conf.d
